language: swift
branches:
  only:
    - master
cache:
  directories:
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
jobs:
  include:
  - script: xcodebuild -scheme DiveKit SWIFT_VERSION=5.1 SUPPORTS_MACCATALYST=NO clean build
    # SUPPORTS_MACCATALYST=NO because Xcode 11 runs on macOS 10.14 in Travis CI
    osx_image: xcode11
    name: "Swift 5.1"
