import XCTest
@testable import DiveKit

final class DKEnrichedAirTests: XCTestCase {
    var diveKit = DiveKit.init()
    var enrichedAir = DKEnrichedAir.init()
    
    // MARK: - Maximum Operating Depth
    func testSaltWaterImperialOneFour() {
        diveKit = DiveKit.init()
        enrichedAir = DKEnrichedAir(with: diveKit)
        // partial pressure 1.4
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 22)), 177)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 23)), 167)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 24)), 159)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 25)), 151)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 26)), 144)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 27)), 138)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 28)), 131)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 29)), 126)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 30)), 121)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 31)), 116)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 32)), 111)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 33)), 107)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 34)), 102)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 35)), 99)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 36)), 95)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 37)), 91)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 38)), 88)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 39)), 85)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 40)), 82)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 41)), 79)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 42)), 76)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 43)), 74)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 44)), 72)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 45)), 69)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 46)), 67)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 47)), 65)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 48)), 63)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 49)), 61)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 50)), 59)
    }
    func testSaltWaterImperialOneSix() {
        diveKit = DiveKit.init()
        enrichedAir = DKEnrichedAir(with: diveKit)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 22)), 207)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 23)), 196)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 24)), 187)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 25)), 178)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 26)), 170)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 27)), 162)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 28)), 155)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 29)), 149)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 30)), 143)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 31)), 137)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 32)), 132)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 33)), 127)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 34)), 122)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 35)), 117)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 36)), 113)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 37)), 109)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 38)), 105)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 39)), 102)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 40)), 99)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 41)), 95)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 42)), 92)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 43)), 89)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 44)), 87)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 45)), 84)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 46)), 81)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 47)), 79)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 48)), 77)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 49)), 74)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 50)), 72)
    }
    func testFreshWaterImperialOneFour() {
        diveKit = DiveKit.init(waterType: .freshWater)
        enrichedAir = DKEnrichedAir(with: diveKit)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 22)), 182)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 23)), 172)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 24)), 164)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 25)), 156)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 26)), 149)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 27)), 142)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 28)), 135)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 29)), 130)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 30)), 124)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 31)), 119)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 32)), 114)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 33)), 110)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 34)), 105)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 35)), 102)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 36)), 98)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 37)), 94)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 38)), 91)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 39)), 88)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 40)), 84)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 41)), 82)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 42)), 79)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 43)), 76)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 44)), 74)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 45)), 71)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 46)), 69)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 47)), 67)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 48)), 65)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 49)), 63)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 50)), 61)
    }
    func testFreshWaterImperialOneSix() {
        diveKit = DiveKit.init(waterType: .freshWater)
        enrichedAir = DKEnrichedAir(with: diveKit)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 22)), 213)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 23)), 202)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 24)), 192)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 25)), 183)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 26)), 175)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 27)), 167)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 28)), 160)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 29)), 153)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 30)), 147)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 31)), 141)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 32)), 136)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 33)), 130)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 34)), 126)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 35)), 121)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 36)), 117)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 37)), 113)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 38)), 109)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 39)), 105)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 40)), 102)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 41)), 98)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 42)), 95)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 43)), 92)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 44)), 89)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 45)), 86)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 46)), 84)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 47)), 81)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 48)), 79)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 49)), 77)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 50)), 74)
    }
    func testSaltWaterMetricOneFour() {
        diveKit = DiveKit.init(measurementUnit: .metric)
        enrichedAir = DKEnrichedAir(with: diveKit)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 22), decimalPlaces: 1), 53.6)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 23), decimalPlaces: 1), 50.9)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 24), decimalPlaces: 1), 48.3)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 25), decimalPlaces: 1), 46)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 26), decimalPlaces: 1), 43.8)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 27), decimalPlaces: 1), 41.9)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 28), decimalPlaces: 1), 40)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 29), decimalPlaces: 1), 38.3)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 30), decimalPlaces: 1), 36.7)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 31), decimalPlaces: 1), 35.2)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 32), decimalPlaces: 1), 33.8)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 33), decimalPlaces: 1), 32.4)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 34), decimalPlaces: 1), 31.2)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 35), decimalPlaces: 1), 30)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 36), decimalPlaces: 1), 28.9)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 37), decimalPlaces: 1), 27.8)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 38), decimalPlaces: 1), 26.8)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 39), decimalPlaces: 1), 25.9)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 40), decimalPlaces: 1), 25)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 50), decimalPlaces: 1), 18)
    }
    func testSaltWaterMetricOneSix() {
        diveKit = DiveKit.init(measurementUnit: .metric)
        enrichedAir = DKEnrichedAir(with: diveKit)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 22), decimalPlaces: 1), 62.7)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 23), decimalPlaces: 1), 59.6)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 24), decimalPlaces: 1), 56.7)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 25), decimalPlaces: 1), 54)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 26), decimalPlaces: 1), 51.5)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 27), decimalPlaces: 1), 49.3)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 28), decimalPlaces: 1), 47.1)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 29), decimalPlaces: 1), 45.2)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 30), decimalPlaces: 1), 43.3)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 31), decimalPlaces: 1), 41.6)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 32), decimalPlaces: 1), 40)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 33), decimalPlaces: 1), 38.5)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 34), decimalPlaces: 1), 37.1)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 35), decimalPlaces: 1), 35.7)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 36), decimalPlaces: 1), 34.4)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 37), decimalPlaces: 1), 33.2)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 38), decimalPlaces: 1), 32.1)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 39), decimalPlaces: 1), 31)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 40), decimalPlaces: 1), 30)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.6, gas: .enrichedAir(percentage: 50), decimalPlaces: 1), 22)
    }
    func testFreshWaterMetrixOneFour() {
        enrichedAir = DKEnrichedAir(waterType: .freshWater, measurementUnit: .metric)
        XCTAssertEqual(try! enrichedAir.maximumOperatingDepth(fractionOxygen: 1.4, gas: .enrichedAir(percentage: 32), decimalPlaces: 2), 34.76)
    }
    
    // MARK: - Equivalent Air Depth
    func testEquivalentAirDepth() {
        var gas = DKGas.enrichedAir(percentage: 36)
        enrichedAir = DKEnrichedAir.init(waterType: .saltWater, measurementUnit: .imperial)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 90, gas: gas), 67)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 33, gas: gas), 20)
        enrichedAir = DKEnrichedAir.init(waterType: .saltWater, measurementUnit: .metric)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 27, gas: gas, decimalPlaces: 2), 19.97)
        gas = DKGas.enrichedAir(percentage: 32)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 35, gas: gas, decimalPlaces: 1), 28.7)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 30.5, gas: gas, decimalPlaces: 1), 24.9)
        gas = DKGas.air
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 35, gas: gas, decimalPlaces: 1), 35)
        enrichedAir = DKEnrichedAir.init(waterType: .saltWater, measurementUnit: .imperial)
        gas = DKGas.enrichedAir(percentage: 32)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 100, gas: gas, decimalPlaces: 1), 81.5)
        enrichedAir = DKEnrichedAir.init(waterType: .freshWater, measurementUnit: .metric)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 30, gas: gas, decimalPlaces: 1), 24.4)
       enrichedAir = DKEnrichedAir.init(waterType: .freshWater, measurementUnit: .imperial)
        XCTAssertEqual(try! enrichedAir.equivalentAirDepth(depth: 110, gas: gas), 90)
    }
    
    // MARK: - Best Blend
    func testBestBlend() {
        enrichedAir = DKEnrichedAir(waterType: .saltWater, measurementUnit: .metric)
        XCTAssertEqual(try! enrichedAir.bestBlend(for: 35, fractionOxygen: 1.4).percentOxygen, 31)
        XCTAssertEqual(try! enrichedAir.bestBlend(for: 25, fractionOxygen: 1.4).percentOxygen, 40)
        enrichedAir = DKEnrichedAir(waterType: .saltWater, measurementUnit: .imperial)
        XCTAssertEqual(try! enrichedAir.bestBlend(for: 100, fractionOxygen: 1.4).percentOxygen, 34)
    }
    
    // MARK: - Inititalizers
    func testEnrichedAirInititalizers() {
        enrichedAir = DKEnrichedAir.init()
        XCTAssertEqual(enrichedAir.diveKit.measurementUnit, DiveKit.MeasurementUnit.imperial)
        XCTAssertEqual(enrichedAir.diveKit.waterType, DiveKit.WaterType.saltWater)
        diveKit = DiveKit.init()
        enrichedAir = DKEnrichedAir.init(with: diveKit)
        XCTAssertEqual(enrichedAir.diveKit.measurementUnit, DiveKit.MeasurementUnit.imperial)
        XCTAssertEqual(enrichedAir.diveKit.waterType, DiveKit.WaterType.saltWater)
        enrichedAir = DKEnrichedAir.init(measurementUnit: .metric)
        XCTAssertEqual(enrichedAir.diveKit.measurementUnit, DiveKit.MeasurementUnit.metric)
        XCTAssertEqual(enrichedAir.diveKit.waterType, DiveKit.WaterType.saltWater)
        enrichedAir = DKEnrichedAir.init(waterType: .freshWater)
        XCTAssertEqual(enrichedAir.diveKit.measurementUnit, DiveKit.MeasurementUnit.imperial)
        XCTAssertEqual(enrichedAir.diveKit.waterType, DiveKit.WaterType.freshWater)
        enrichedAir = DKEnrichedAir.init(waterType: .freshWater, measurementUnit: .metric)
        XCTAssertEqual(enrichedAir.diveKit.measurementUnit, DiveKit.MeasurementUnit.metric)
        XCTAssertEqual(enrichedAir.diveKit.waterType, DiveKit.WaterType.freshWater)
    }
    
    func testThrows() {
        let gas = DKGas.air
        let errorGas = DKGas.enrichedAir(percentage: -20)
        XCTAssertThrowsError(try enrichedAir.bestBlend(for: 25, fractionOxygen: -1.4))
        XCTAssertThrowsError(try enrichedAir.bestBlend(for: -25, fractionOxygen: 1.4))
        XCTAssertThrowsError(try enrichedAir.maximumOperatingDepth(fractionOxygen: -2, gas: gas, decimalPlaces: 2))
        XCTAssertThrowsError(try enrichedAir.maximumOperatingDepth(fractionOxygen: 2, gas: errorGas, decimalPlaces: 2))
        XCTAssertThrowsError(try enrichedAir.maximumOperatingDepth(fractionOxygen: 2, gas: gas, decimalPlaces: -2))
        
        XCTAssertThrowsError(try enrichedAir.equivalentAirDepth(depth: -2, gas: gas, decimalPlaces: 2))
        XCTAssertThrowsError(try enrichedAir.equivalentAirDepth(depth: 2, gas: errorGas, decimalPlaces: 2))
        XCTAssertThrowsError(try enrichedAir.equivalentAirDepth(depth: 2, gas: gas, decimalPlaces: -2))
        
        XCTAssertThrowsError(try enrichedAir.exceedsMaximumOperatingDepth(with: errorGas, fractionOxygen: 2, depth: 2))
        XCTAssertThrowsError(try enrichedAir.exceedsMaximumOperatingDepth(with: gas, fractionOxygen: -2, depth: 2))
        XCTAssertThrowsError(try enrichedAir.exceedsMaximumOperatingDepth(with: gas, fractionOxygen: 2, depth: -2))
    }
    
    static var allTests = [
        ("testSaltWaterImperialOneFour", testSaltWaterImperialOneFour),
        ("testSaltWaterImperialOneSix", testSaltWaterImperialOneSix),
        ("testFreshWaterImperialOneFour", testFreshWaterImperialOneFour),
        ("testFreshWaterImperialOneSix", testFreshWaterImperialOneSix),
        ("testSaltWaterMetricOneFour", testSaltWaterMetricOneFour),
        ("testSaltWaterMetricOneSix", testSaltWaterMetricOneSix),
        ("testEquivalentAirDepth", testEquivalentAirDepth),
        ("testEnrichedAirInititalizers", testEnrichedAirInititalizers)
    ]
}
