# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CODECOV_JSON: .build/debug/codecov/DiveKit.json

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10.0"
    - name: Get swift version
      run: swift --version # Swift 5.10.0
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run Tests and Generate lcov File
      run: swift test --enable-code-coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{ env.CODECOV_JSON }}
        slug: jaytrisw/DiveKit2
